name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'source/**'
    - '.github/workflows/**'
    - 'CMakeLists.txt'
    - 'CMakePresets.json'
    - 'vcpkg.json'
    - 'vcpkg-configuration.json'


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_ubuntu:
    name: Ubuntu
    runs-on: ubuntu-${{ matrix.os }}
    strategy:
      matrix:
        os: [22.04, 24.04]
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install development dependencies
      run: |
        sudo rm /etc/apt/sources.list.d/* && sudo dpkg --clear-avail # Speed up installation and get rid of unwanted lists
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends autoconf-archive
        # sudo apt-get install -y --no-install-recommends libx11-xcb-dev
        # sudo apt-get install -y --no-install-recommends libxrender-dev
        # sudo apt-get install -y --no-install-recommends libxkbcommon-x11-dev
        # sudo apt-get install -y --no-install-recommends libxmu-dev
        # sudo apt-get install -y --no-install-recommends libxi-dev
        # sudo apt-get install -y --no-install-recommends libgl-dev
        # sudo apt-get install -y --no-install-recommends libglu1-mesa-dev
        # sudo apt-get install -y --no-install-recommends libgles2-mesa-dev
        # sudo apt-get install -y --no-install-recommends libwayland-dev
        # sudo apt-get install -y --no-install-recommends libxkbcommon-dev
        # sudo apt-get install -y --no-install-recommends libegl1-mesa-dev
        # sudo apt-get install -y --no-install-recommends libosmesa6
        # sudo apt-get install -y --no-install-recommends mesa-utils
        # sudo apt-get install -y --no-install-recommends libglvnd-dev
        # sudo apt-get install -y --no-install-recommends x11-utils
        # sudo apt-get install -y --no-install-recommends '^libxcb.*-dev'
    - uses: lukka/get-cmake@v3.28.3
    - uses: lukka/run-vcpkg@v11
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'linux-release'
        buildPreset: 'linux-ci-release'


  build_windows:
    name: Windows
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - uses: lukka/get-cmake@v3.28.3
    - uses: lukka/run-vcpkg@v11
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'mingw-release'
        buildPreset: 'mingw-ci-release'


  build_windows_clang:
    name: Windows Clang
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - uses: lukka/get-cmake@v3.28.3
    - uses: lukka/run-vcpkg@v11
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'clang-cl-release'
        buildPreset: 'clang-cl-ci-release'


  build_macos:
    name: MacOS
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install pkg-config
      run: brew install automake autoconf-archive
    - uses: lukka/get-cmake@v3.28.3
    - uses: lukka/run-vcpkg@v11
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'macos-release'
        buildPreset: 'macos-ci-release'

