name: CI

on:
  push:
    branches:
      - master
      - next
      - releases/v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'source/**'
    - '.github/workflows/**'
    - 'CMakeLists.txt'
    - 'CMakePresets.json'
    - 'vcpkg.json'
    - 'vcpkg-configuration.json'


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_ubuntu:
    name: Ubuntu
    runs-on: ubuntu-${{ matrix.os }}
    strategy:
      matrix:
        os: [20.04, 22.04]
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install development dependencies
      run: |
        sudo rm /etc/apt/sources.list.d/* && sudo dpkg --clear-avail # Speed up installation and get rid of unwanted lists
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends autoconf-archive libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libgles2-mesa-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev libosmesa6 mesa-utils libglvnd-dev x11-utils
    - uses: lukka/get-cmake@3.26.4
    - uses: lukka/run-vcpkg@v11
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'linux-release'
        buildPreset: 'linux-ci-release'


  build_windows:
    name: Windows
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - uses: lukka/get-cmake@3.26.4
    - uses: lukka/run-vcpkg@v11
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'mingw-release'
        buildPreset: 'mingw-ci-release'


  build_windows_clang:
    name: Windows Clang
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - uses: lukka/get-cmake@3.26.4
    - uses: lukka/run-vcpkg@v11
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'clang-cl-release'
        buildPreset: 'clang-cl-ci-release'


  build_macos:
    name: MacOS
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install pkg-config
      run: brew install automake
    - uses: lukka/get-cmake@3.26.4
    - uses: lukka/run-vcpkg@v11
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'macos-release'
        buildPreset: 'macos-ci-release'

